-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.trips
(
    id bigint NOT NULL DEFAULT nextval('seq_trips_id'::regclass),
    route_id bigint NOT NULL,
    operator character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    bus_type character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    departure_time timestamp without time zone NOT NULL,
    arrival_time timestamp without time zone NOT NULL,
    price numeric(10, 2) NOT NULL DEFAULT 0.00,
    seats_total integer NOT NULL DEFAULT 0,
    seats_available integer NOT NULL DEFAULT 0,
    status character varying(9) COLLATE pg_catalog."default" NOT NULL DEFAULT 'scheduled'::character varying,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bus_id bigint,
    driver_id bigint,
    CONSTRAINT trips_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.buses
(
    id serial NOT NULL,
    number_plate character varying(20) COLLATE pg_catalog."default",
    bus_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    seat_layout jsonb,
    total_seats integer,
    image_url text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    CONSTRAINT buses_pkey PRIMARY KEY (id),
    CONSTRAINT buses_number_plate_key UNIQUE (number_plate)
);

CREATE TABLE IF NOT EXISTS public.drivers
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    license_number character varying(50) COLLATE pg_catalog."default",
    experience_years integer DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    CONSTRAINT drivers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.routes
(
    id bigint NOT NULL DEFAULT nextval('seq_routes_id'::regclass),
    origin character varying(255) COLLATE pg_catalog."default" NOT NULL,
    destination character varying(255) COLLATE pg_catalog."default" NOT NULL,
    distance_km integer,
    duration_min integer,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description text COLLATE pg_catalog."default",
    base_price numeric(10, 2) DEFAULT 0,
    CONSTRAINT routes_pkey PRIMARY KEY (id),
    CONSTRAINT routes_origin_destination_key UNIQUE (origin, destination)
);

CREATE TABLE IF NOT EXISTS public.route_stops
(
    id bigserial NOT NULL,
    route_id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    type character varying(20) COLLATE pg_catalog."default" DEFAULT 'both'::character varying,
    order_index integer NOT NULL,
    estimate_time time without time zone,
    CONSTRAINT route_stops_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    id bigint NOT NULL DEFAULT nextval('seq_bookings_id'::regclass),
    user_id integer NOT NULL,
    trip_id bigint NOT NULL,
    price_paid numeric(10, 2) NOT NULL DEFAULT 0.00,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount numeric(10, 2),
    promotion_code character varying(50) COLLATE pg_catalog."default",
    seats_count integer DEFAULT 1,
    cancelled_at timestamp without time zone,
    payment_id bigint,
    metadata jsonb,
    pickup_stop_id bigint,
    dropoff_stop_id bigint,
    CONSTRAINT bookings_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.bookings.status
    IS 'Booking status: pending, confirmed, cancelled, pending_refund, refunded';

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('seq_users_id'::regclass),
    name character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    email character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    password character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    otp_code character varying(6) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    status character varying(7) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    phone character varying(15) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'user'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_sdt_key UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    id bigserial NOT NULL,
    user_id bigint,
    trip_id bigint,
    rating integer,
    comment text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.promotions
(
    id bigserial NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    discount_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    discount_value numeric(10, 2) NOT NULL,
    min_price numeric(10, 2) DEFAULT 0,
    max_discount numeric(10, 2) DEFAULT 0,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    CONSTRAINT promotions_pkey PRIMARY KEY (id),
    CONSTRAINT promotions_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id bigserial NOT NULL,
    booking_id bigint,
    amount numeric(10, 2),
    method character varying(50) COLLATE pg_catalog."default",
    transaction_id character varying(255) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.booking_items
(
    id bigserial NOT NULL,
    booking_id bigint,
    seat_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    CONSTRAINT booking_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.seats
(
    id bigint NOT NULL DEFAULT nextval('seq_seats_id'::regclass),
    trip_id bigint NOT NULL,
    label character varying(32) COLLATE pg_catalog."default" NOT NULL,
    type character varying(4) COLLATE pg_catalog."default" DEFAULT 'seat'::character varying,
    is_booked integer NOT NULL DEFAULT 0,
    booking_id bigint,
    CONSTRAINT seats_pkey PRIMARY KEY (id),
    CONSTRAINT seats_trip_id_label_key UNIQUE (trip_id, label)
);

ALTER TABLE IF EXISTS public.trips
    ADD CONSTRAINT fk_trips_bus FOREIGN KEY (bus_id)
    REFERENCES public.buses (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.trips
    ADD CONSTRAINT fk_trips_driver FOREIGN KEY (driver_id)
    REFERENCES public.drivers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trips
    ADD CONSTRAINT trips_ibfk_1 FOREIGN KEY (route_id)
    REFERENCES public.routes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.route_stops
    ADD CONSTRAINT route_stops_route_id_fkey FOREIGN KEY (route_id)
    REFERENCES public.routes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_dropoff_stop_id_fkey FOREIGN KEY (dropoff_stop_id)
    REFERENCES public.route_stops (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_ibfk_1 FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_ibfk_2 FOREIGN KEY (trip_id)
    REFERENCES public.trips (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_pickup_stop_id_fkey FOREIGN KEY (pickup_stop_id)
    REFERENCES public.route_stops (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT fk_booking_promo FOREIGN KEY (promotion_code)
    REFERENCES public.promotions (code) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT fk_bookings_payment FOREIGN KEY (payment_id)
    REFERENCES public.payments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk_reviews_trip FOREIGN KEY (trip_id)
    REFERENCES public.trips (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk_reviews_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_trip_id_fkey FOREIGN KEY (trip_id)
    REFERENCES public.trips (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.bookings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.booking_items
    ADD CONSTRAINT booking_items_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.bookings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.seats
    ADD CONSTRAINT fk_seats_booking FOREIGN KEY (booking_id)
    REFERENCES public.bookings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.seats
    ADD CONSTRAINT fk_seats_trip FOREIGN KEY (trip_id)
    REFERENCES public.trips (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.seats
    ADD CONSTRAINT seats_ibfk_1 FOREIGN KEY (trip_id)
    REFERENCES public.trips (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.seats
    ADD CONSTRAINT seats_ibfk_2 FOREIGN KEY (booking_id)
    REFERENCES public.bookings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;